apiVersion: v1
kind: Service
metadata:
  name: csharp-api
  namespace: default
spec:
  ports:
    - port: 5250
      targetPort: 5250
      nodePort: 30002
  selector:
    app: csharp-app
  type: NodePort