apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-app
  template:
    metadata:
      labels:
        app: csharp-app
    spec:
      containers:
        - name: csharp-api
          image: csharp-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5250
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "5250"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:5250"
